title: Kalen Daniel
description: My Portfolio of Data Science, Smart Home, My Career, & Existential food for your soul...
author: Kalen Daniel
email: kalendaniel@gmail.com
phone: (503) 841-7971
github: https://github.com/thesmarthomeninja
about: I am an Analyst and Citizen Data Scientist for <a href="https://www.build.com" target="_blank">Build.com</a> and a freelance web developer, web analytics auditor, analyst, and smart home consultant.
disqus_shortname: analytics_ninja
google_analytics: UA-78444465-3
avatar_url: /static/img/me.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/thesmarthomeninja"
    - icon: fa-twitter
      link: "https://twitter.com/smarthomeninja"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/theanalyticsninja/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/thesmarthomeninja"

share:
  twitter_username: smarthomeninja
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
    - text: XML Feed
      url: /feed.xml
# url: "http://localhost:4000"
url: "https://thesmarthomeninja.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
